//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTeslim
    {
        public int teslimID { get; set; }
        public Nullable<int> aracID { get; set; }
        public Nullable<int> musteriID { get; set; }
        public Nullable<long> kullanilanKm { get; set; }
        public Nullable<bool> kmSiniriniGectiMi { get; set; }
        public Nullable<System.DateTime> teslimTarihi { get; set; }
    
        public virtual tblArac tblArac { get; set; }
        public virtual tblMusteri tblMusteri { get; set; }
    }
}
